# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock .
COPY main.py README.md LICENSE .
COPY img ./img

# Install dependencies
RUN pip install --no-cache-dir .

# Expose no HTTP port since stdio

# Default command
CMD ["python", "main.py"]
